### ISSUE TITLE
Anyone else having problem with the latest Chrome verson?

### ISSUE THREAD

**Issue by angelformica** [felicegattuso/datedropper#101]
Hello everybody! Maybe someone can help me?

My datedropper stoped working with chrome, on click it opens the popup but immediately closes without giving opportunity to select a date.

It works on safari,

**Comment by sanjit-dasgupta** [comment]
I have the same problem. Though the popup works normally if I right click the textbox. But when I left click it (or tap the textbox on mobile devices), the popup appears and then immediately closes. Any luck isolating the problem ?

**Comment by angelformica** [comment]
The only way I was able to get it to work was to change the datedrpper
layout to small

**Comment by sanjit-dasgupta** [comment]
Oh. I'll try that too. 

For now, I changed the datedropper.js file. I set a variable pick_click to true on mouseup event. And on click event, I checked that if it is false, then close the popup, else do nothing. Initially, chrome executed the mouseup(which initializes the datedropper) and click(which hides the datedropper) events simultaneously, because of which the problem occurred. 

Obviously, this is a quick fix and the problem still persists on chrome for mobile devices. One workaround is to long press the input field to show the datedropper, but we can't rely on the end user figuring that out on his own, since the natural course of action is to tap once. If I find anything new, I'll post it here.

**Comment by anujithramanan** [comment]
I fixed this in chrome mobile, just add pick_click = true in //MOUSEDOWN ON UL event

**Comment by nolyboms** [comment]
@angelformica as of now the bug still exists and makes this great widget kind of useless. I think this plugin is not maintained anymore too since the developer didn't respond on contact via mail - which is sad since i belong to those guys having paid for the pro version which is now free of charge.

Anyway...i hope you guys could help me with a tweak to get this beautiful widget running.

@angelformica How did you set the layout to small?
@sanjit-dasgupta Can you please provide your "hack" so that anyone else can profit from your solution?
@anujithramanan to which code part did you add that? I can't find that option in the official  documentation.
